import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { createResourceProtocol } = require('../.test-build/lib/hosted/resourceProtocol.js');
const policy = { issuer: 'https://issuer.example.test', resource: 'https://mcp.example.test/api/mcp', jwksUrl: 'https://issuer.example.test/keys', allowedClientIds: ['test-client'], requiredScopes: ['routerlens:read'], algorithms: ['ES256'] };

test('protected resource discovery is generated by mcp-handler for the exact trusted resource', async () => {
  const protocol = createResourceProtocol(policy);
  assert.equal(protocol.metadataUrl, 'https://mcp.example.test/.well-known/oauth-protected-resource/api/mcp');
  assert.deepEqual(await protocol.metadata().json(), { resource: policy.resource, authorization_servers: [policy.issuer], scopes_supported: ['routerlens:read'], bearer_methods_supported: ['header'] });
});
test('401 and 403 challenges disclose only standard errors and trusted metadata locations', async () => {
  const protocol = createResourceProtocol(policy);
  for (const status of [401, 403]) {
    const response = protocol.challenge(status);
    assert.equal(response.status, status);
    assert.equal(response.headers.get('cache-control'), 'no-store');
    assert.match(response.headers.get('www-authenticate'), /resource_metadata="https:\/\/mcp\.example\.test\/\.well-known\/oauth-protected-resource\/api\/mcp"/);
    assert.match(response.headers.get('www-authenticate'), /scope="routerlens:read"/);
    assert.deepEqual(await response.json(), { error: status === 401 ? 'invalid_token' : 'insufficient_scope' });
  }
});
test('metadata/challenge factories reject unsafe URLs and header-injection scope values', () => {
  for (const scope of ['bad"scope', 'bad\\scope', 'bad\nscope', '', 'two scopes']) assert.throws(() => createResourceProtocol({ ...policy, requiredScopes: [scope] }));
  for (const issuer of ['https://localhost.', 'https://127.0.0.1', 'http://issuer.example.test']) assert.throws(() => createResourceProtocol({ ...policy, issuer }));
  const protocol = createResourceProtocol(policy);
  assert.throws(() => protocol.challenge(403, ['unlisted:write']));
  assert.throws(() => protocol.challenge(403, []));
});
